### ISSUE TITLE
Error in compile the code

### ISSUE THREAD

**Issue by mamanbudiman** [pulsartronic/LoRaWANGatewaySC#2]
I try to compile the code, according to this guide
https://www.hackster.io/pulsartronic/lorawan-gateway-esp8266-rfm95-arduino-4914a8

There is an exit error when I compile it.
`Using library WAN in folder: C:\Users\user\Documents\Arduino\LoRaWANGatewaySC-master\libraries\WAN (legacy)
Using library DataStructure in folder: C:\Users\user\Documents\Arduino\LoRaWANGatewaySC-master\libraries\DataStructure (legacy)
Using library Hash at version 1.0 in folder: C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1\libraries\Hash 
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.`

I use Arduino IDE 1.8.10

Any suggestion ?

Regards

**Comment by pulsartronic** [comment]
Hello, i see you are using esp8266 v2.7.1 ... it wasn't tested using that version ... try to install esp8266 2.6.3 till i have the time to update the code ... thanks
![2 6 3](https://user-images.githubusercontent.com/59339572/84588943-bc0cbe80-ae2b-11ea-8aec-d1b7a010b7a9.jpg)

**Comment by pulsartronic** [comment]
It is fixed ... now it works with v2.7.1

**Comment by mamanbudiman** [comment]
Ok, thank you.

Regards,
